server:
  port: 10001

spring:
  rabbitmq:
    host: sucifitz.top
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual

